name: container-images


on:
  push:
    branches: [ "acex-test" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1

    - run: echo "IMAGE_TAG=acex-deploy" >> $GITHUB_ENV
      if: github.ref_name == 'acex-test'

    - name: Login to ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push default image
      uses: docker/build-push-action@v5
      with:
        context: . # Because GH actions are for kids and put protection on everything; https://stackoverflow.com/a/71159809/11276254
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}