name: binaries


on:
  workflow_dispatch:
  push:
    branches:
    tags:

env:
  go_version: 1.22

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.go_version }}


    - run: echo "IMAGE_TAG=acex-deploy" >> $GITHUB_ENV
      if: ${{ github.ref_name }} == 'acex-test'
    - run: echo "IMAGE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
      if: startsWith(github.ref, 'refs/tags/v')
    
    - run: sudo apt-get update -y && sudo apt-get install -y rsync
    - name: build
      env:
        GOPATH: /home/runner/work/go-songbird/go
      id: build
      run: |
        cd avalanchego
        ./scripts/build.sh

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-bin
        path: |
          avalanchego/build
